//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_MUON
    {
        public string Ma_Phieu_muon { get; set; }
        public string Ma_Khach_hang { get; set; }
        public string Ma_Sach { get; set; }
        public Nullable<System.DateTime> Ngay_muon { get; set; }
        public Nullable<System.DateTime> Han_tra { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Ngaytra { get; set; }
        public Nullable<int> TienDatCoc { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
